// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/coze-dev/coze-loop/backend/pkg/conf/viper"
	"github.com/coze-dev/coze-loop/backend/pkg/logs"
	"golang.org/x/oauth2"

	"github.com/coze-dev/coze-loop/backend/infra/middleware/session"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/foundation/user"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/foundation/user/userservice"
	"github.com/coze-dev/coze-loop/backend/pkg/hertzutil"
)

var localUserClient userservice.Client

// Register .
// @router /api/foundation/v1/users/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, func(ctx context.Context, request *user.UserRegisterRequest, callOptions ...callopt.Option) (r *user.UserRegisterResponse, err error) {
		r, err = localUserClient.Register(ctx, request, callOptions...)
		if err != nil {
			return nil, err
		}
		if r.Token != nil {
			c.SetCookie(session.SessionKey,
				r.GetToken(),
				int(r.GetExpireTime()),
				"/",
				hertzutil.GetOriginHost(c),
				protocol.CookieSameSiteDefaultMode,
				false,
				true)
		}
		return r, nil
	})
}

// ResetPassword .
// @router /api/foundation/v1/users/reset_password [POST]
func ResetPassword(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localUserClient.ResetPassword)
}

// LoginByPassword .
// @router /api/foundation/v1/users/login_by_password [POST]
func LoginByPassword(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, func(ctx context.Context, request *user.LoginByPasswordRequest, callOptions ...callopt.Option) (r *user.LoginByPasswordResponse, err error) {
		r, err = localUserClient.LoginByPassword(ctx, request, callOptions...)
		if err != nil {
			return nil, err
		}
		if r.Token != nil {
			c.SetCookie(session.SessionKey,
				*r.Token,
				int(*r.ExpireTime),
				"/",
				hertzutil.GetOriginHost(c),
				protocol.CookieSameSiteDefaultMode,
				false,
				true)
		}
		return r, nil
	})
}

// Logout .
// @router /api/foundation/v1/users/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, func(ctx context.Context, request *user.LogoutRequest, callOptions ...callopt.Option) (r *user.LogoutResponse, err error) {
		r, err = localUserClient.Logout(ctx, request, callOptions...)
		if err != nil {
			return nil, err
		}
		c.SetCookie(session.SessionKey,
			"",
			-1,
			"/",
			hertzutil.GetOriginHost(c),
			protocol.CookieSameSiteDefaultMode,
			false,
			true)
		return r, nil
	})
}

// ModifyUserProfile .
// @router /api/foundation/v1/users/update_profile [POST]
func ModifyUserProfile(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localUserClient.ModifyUserProfile)
}

// GetUserInfoByToken .
// @router /api/foundation/v1/users/session [GET]
func GetUserInfoByToken(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localUserClient.GetUserInfoByToken)
}

type UserInfo struct {
	ID          int    `json:"id"`
	Login       string `json:"login"`
	Email       string `json:"email"`
	Name        string `json:"name"`
	AvatarURL   string `json:"avatar_url"`
	Bio         string `json:"bio"`
	Location    string `json:"location"`
	Blog        string `json:"blog"`
	Company     string `json:"company"`
	PublicRepos int    `json:"public_repos"`
	Followers   int    `json:"followers"`
	Following   int    `json:"following"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func LoginByOAuth(ctx context.Context, c *app.RequestContext) {
	code := c.Query("code")
	logs.CtxInfo(ctx, "code: %s", code)
	invokeAndRender(ctx, c, func(ctx context.Context, request *user.LoginByOAuthRequest, callOptions ...callopt.Option) (r *user.LoginByPasswordResponse, err error) {
		provider := request.Provider
		providers, done := loadProviders(ctx, c)
		providerProperties := providers[*provider]

		properties := providers[*provider]
		config := oauth2.Config{
			ClientID:     *properties.ClientID,
			ClientSecret: *properties.ClientSecret,
			Endpoint:     oauth2.Endpoint{},
			RedirectURL:  *properties.RedirectURL,
			Scopes:       nil,
		}
		token, err := config.Exchange(ctx, *request.Code)
		client := config.Client(ctx, token)
		resp, err := client.Get(*properties.UserInfoURL)
		if err != nil {
			return nil, fmt.Errorf("get user info failed: %w", err)
		}
		if resp.StatusCode != 200 {
			return nil, fmt.Errorf("get user info failed, status code: %d", resp.StatusCode)
		}
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, fmt.Errorf("read response body failed: %w", err)
		}
		var userInfo UserInfo
		if err := json.Unmarshal(body, &userInfo); err != nil {
			return nil, fmt.Errorf("failed to unmarshal user info: %w", err)
		}
		var password = "123456qwer!@#$"
		registerRequest := &user.UserRegisterRequest{
			Email:    &userInfo.Email,
			Password: &password,
		}
		_, err = localUserClient.Register(ctx, registerRequest)
		r, err = localUserClient.LoginByPassword(ctx, &user.LoginByPasswordRequest{
			Email:    &userInfo.Email,
			Password: &password,
		})
		if err != nil {
			return nil, err
		}
		if done {
			return
		}
		if r.Token != nil {
			c.SetCookie(session.SessionKey,
				*r.Token,
				int(*r.ExpireTime),
				"/",
				hertzutil.GetOriginHost(c),
				protocol.CookieSameSiteDefaultMode,
				false,
				true)
			c.Redirect(302, []byte(*providerProperties.RedirectURL))
		}
		return r, nil
	})
}

func loadProviders(ctx context.Context, c *app.RequestContext) (map[string]*user.OAuthProperties, bool) {
	cfgFactory := viper.NewFileConfigLoaderFactory(viper.WithFactoryConfigPath("conf"))
	loader, err := cfgFactory.NewConfigLoader("oauth.yaml")
	if err != nil {
		c.Error(err)
		return nil, true
	}

	// Step 1: 先加载 oauth 下的内容到 map
	providersMap := make(map[string]*user.OAuthProperties)
	if err := loader.UnmarshalKey(ctx, "oauth", &providersMap); err != nil {
		c.Error(fmt.Errorf("failed to unmarshal oauth config: %w", err))
		return nil, true
	}
	return providersMap, false
}

// GetOAuthProviders .
// @router /api/foundation/v1/users/providers [GET]
func GetOAuthProviders(ctx context.Context, c *app.RequestContext) {
	providersMap, done := loadProviders(ctx, c)
	if done {
		return
	}
	response := user.GetProviderResponse{
		Providers: providersMap,
	}
	c.JSON(200, response)
}
