// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/foundation/auth"
	"github.com/coze-dev/coze-loop/backend/modules/data/domain/component/conf"
	"github.com/coze-dev/coze-loop/backend/pkg/conf/viper"
	"github.com/coze-dev/coze-loop/backend/pkg/logs"

	"github.com/coze-dev/coze-loop/backend/infra/middleware/session"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/foundation/user"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/foundation/user/userservice"
	"github.com/coze-dev/coze-loop/backend/pkg/hertzutil"
)

var localUserClient userservice.Client

// Register .
// @router /api/foundation/v1/users/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, func(ctx context.Context, request *user.UserRegisterRequest, callOptions ...callopt.Option) (r *user.UserRegisterResponse, err error) {
		r, err = localUserClient.Register(ctx, request, callOptions...)
		if err != nil {
			return nil, err
		}
		if r.Token != nil {
			c.SetCookie(session.SessionKey,
				r.GetToken(),
				int(r.GetExpireTime()),
				"/",
				hertzutil.GetOriginHost(c),
				protocol.CookieSameSiteDefaultMode,
				false,
				true)
		}
		return r, nil
	})
}

// ResetPassword .
// @router /api/foundation/v1/users/reset_password [POST]
func ResetPassword(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localUserClient.ResetPassword)
}

// LoginByPassword .
// @router /api/foundation/v1/users/login_by_password [POST]
func LoginByPassword(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, func(ctx context.Context, request *user.LoginByPasswordRequest, callOptions ...callopt.Option) (r *user.LoginByPasswordResponse, err error) {
		r, err = localUserClient.LoginByPassword(ctx, request, callOptions...)
		if err != nil {
			return nil, err
		}
		if r.Token != nil {
			c.SetCookie(session.SessionKey,
				*r.Token,
				int(*r.ExpireTime),
				"/",
				hertzutil.GetOriginHost(c),
				protocol.CookieSameSiteDefaultMode,
				false,
				true)
		}
		return r, nil
	})
}

// Logout .
// @router /api/foundation/v1/users/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, func(ctx context.Context, request *user.LogoutRequest, callOptions ...callopt.Option) (r *user.LogoutResponse, err error) {
		r, err = localUserClient.Logout(ctx, request, callOptions...)
		if err != nil {
			return nil, err
		}
		c.SetCookie(session.SessionKey,
			"",
			-1,
			"/",
			hertzutil.GetOriginHost(c),
			protocol.CookieSameSiteDefaultMode,
			false,
			true)
		return r, nil
	})
}

// ModifyUserProfile .
// @router /api/foundation/v1/users/update_profile [POST]
func ModifyUserProfile(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localUserClient.ModifyUserProfile)
}

// GetUserInfoByToken .
// @router /api/foundation/v1/users/session [GET]
func GetUserInfoByToken(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localUserClient.GetUserInfoByToken)
}

func LoginByOAuth(ctx context.Context, c *app.RequestContext) {
	code := c.Query("code")
	logs.CtxInfo(ctx, "code: %s", code)
	c.Redirect(302, []byte("https://www.baidu.com"))
}

func GetOauthProviders(ctx context.Context, c *app.RequestContext) {
	cfgFactory := viper.NewFileConfigLoaderFactory(viper.WithFactoryConfigPath("conf"))
	loader, err := cfgFactory.NewConfigLoader("oauth.yaml")
	if err != nil {
		c.Error(err)
		return
	}

	// Step 1: 先加载 oauth 下的内容到 map
	providersMap := make(map[string]conf.OauthProperties)
	if err := loader.UnmarshalKey(ctx, "oauth", &providersMap); err != nil {
		c.Error(fmt.Errorf("failed to unmarshal oauth config: %w", err))
		return
	}

	// Step 2: 包装成你的响应结构体
	response := &auth.OAuthProviderResponse{
		Providers: providersMap,
	}

	c.JSON(200, response)
}
