oauth:
  github:
    mapping:
      mail: mail
    clientId: Ov23lilpja29OqVSsyoN
    clientSecret: 7102ca0ae34b4d094041d29f7d7cddca811d2486
    authUrl: https://github.com/login/oauth/authorize
    tokenUrl: https://github.com/login/oauth/access_token
    userInfoUrl: https://api.github.com/user
    redirectUrl: http://127.0.0.1:8082/api/foundation/v1/users/login_by_oauth
  google:
    mapping:
      mail: mail
    clientId: Ov23lilpja29OqVSsyoN
    clientSecret: 7102ca0ae34b4d094041d29f7d7cddca811d2486
    authUrl: https://github.com/login/oauth/authorize
    tokenUrl: https://github.com/login/oauth/access_token
    userInfoUrl: https://api.github.com/user
    redirectUrl: http://127.0.0.1:8082/api/foundation/v1/users/login_by_oauth